name: Preview Deployment

on:
  pull_request:
    branches: [ master, main ]
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies (bun)
        run: |
          cd frontend
          bun install

      - name: Build project (Nuxt)
        run: |
          cd frontend
          bun run build
        env:
          NUXT_PUBLIC_API_URL: ${{ secrets.NUXT_PUBLIC_API_URL }}
          NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY }}

      - name: Build Vercel prebuilt output
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        run: |
          cd frontend
          npx vercel build --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}

      - name: Deploy to Vercel Preview
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          github-comment: true
          vercel-args: '--prebuilt'
          working-directory: ./frontend

      - name: Comment PR
        uses: actions/github-script@v7
        if: success()
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Preview deployment completed! Check the deployment URL above.'
            })
